/**
 * Service for interacting with the actual board.
*/
moon.factory('moonboard', function ($q, $document, database) {
    'use strict';

    var board = {
        holds2016: [
            { img: 1, loc: 'H7', dir: 'SE' },
            { img: 2, loc: 'J14', dir: 'NW' },
            { img: 3, loc: 'K7', dir: 'N' },
            { img: 4, loc: 'D8', dir: 'N' },
            { img: 5, loc: 'A16', dir: 'NW' },
            { img: 6, loc: 'F6', dir: 'E' },
            { img: 7, loc: 'K6', dir: 'N' },
            { img: 8, loc: 'C9', dir: 'W' },
            { img: 9, loc: 'A10', dir: 'SW' },
            { img: 10, loc: 'I8', dir: 'N' },
            { img: 11, loc: 'K12', dir: 'N' },
            { img: 12, loc: 'A11', dir: 'SE' },
            { img: 13, loc: 'B7', dir: 'S' },
            { img: 14, loc: 'D16', dir: 'N' },
            { img: 15, loc: 'K10', dir: 'S' },
            { img: 16, loc: 'G16', dir: 'N' },
            { img: 17, loc: 'F8', dir: 'N' },
            { img: 18, loc: 'F15', dir: 'N' },
            { img: 19, loc: 'G7', dir: 'SW' },
            { img: 20, loc: 'H15', dir: 'NE' },
            { img: 21, loc: 'C12', dir: 'N' },
            { img: 22, loc: 'D6', dir: 'N' },
            { img: 23, loc: 'D3', dir: 'S' },
            { img: 24, loc: 'D13', dir: 'N' },
            { img: 25, loc: 'J11', dir: 'N' },
            { img: 26, loc: 'A13', dir: 'N' },
            { img: 27, loc: 'G11', dir: 'E' },
            { img: 28, loc: 'H18', dir: 'N' },
            { img: 29, loc: 'B4', dir: 'SW' },
            { img: 30, loc: 'K8', dir: 'N' },
            { img: 31, loc: 'C15', dir: 'NW' },
            { img: 32, loc: 'H9', dir: 'E' },
            { img: 33, loc: 'D10', dir: 'NW' },
            { img: 34, loc: 'H14', dir: 'W' },
            { img: 35, loc: 'I5', dir: 'N' },
            { img: 36, loc: 'I12', dir: 'SW' },
            { img: 37, loc: 'K13', dir: 'N' },
            { img: 38, loc: 'C7', dir: 'N' },
            { img: 39, loc: 'C18', dir: 'N' },
            { img: 40, loc: 'F9', dir: 'N' },
            { img: 50, loc: 'C14', dir: 'N' },
            { img: 51, loc: 'D17', dir: 'N' },
            { img: 52, loc: 'D9', dir: 'NE' },
            { img: 53, loc: 'F7', dir: 'NW' },
            { img: 54, loc: 'F12', dir: 'E' },
            { img: 55, loc: 'G12', dir: 'NE' },
            { img: 56, loc: 'B11', dir: 'NW' },
            { img: 57, loc: 'J10', dir: 'NE' },
            { img: 58, loc: 'J2', dir: 'SE' },
            { img: 59, loc: 'E13', dir: 'N' },
            { img: 60, loc: 'I6', dir: 'NE' },
            { img: 61, loc: 'J9', dir: 'SE' },
            { img: 62, loc: 'F14', dir: 'NW' },
            { img: 63, loc: 'I13', dir: 'E' },
            { img: 64, loc: 'E10', dir: 'NW' },
            { img: 65, loc: 'F10', dir: 'NE' },
            { img: 66, loc: 'E15', dir: 'NW' },
            { img: 67, loc: 'B8', dir: 'N' },
            { img: 68, loc: 'A12', dir: 'E' },
            { img: 69, loc: 'I16', dir: 'NE' },
            { img: 70, loc: 'I11', dir: 'N' },
            { img: 71, loc: 'B16', dir: 'NW' },
            { img: 72, loc: 'E11', dir: 'N' },
            { img: 73, loc: 'H11', dir: 'W' },
            { img: 74, loc: 'E7', dir: 'S' },
            { img: 75, loc: 'D12', dir: 'N' },
            { img: 76, loc: 'J8', dir: 'N' },
            { img: 77, loc: 'B13', dir: 'NW' },
            { img: 78, loc: 'B9', dir: 'NE' },
            { img: 79, loc: 'C10', dir: 'NE' },
            { img: 80, loc: 'B3', dir: 'SW' },
            { img: 81, loc: 'G2', dir: 'N' },
            { img: 82, loc: 'G18', dir: 'W' },
            { img: 83, loc: 'I4', dir: 'NE' },
            { img: 84, loc: 'K11', dir: 'NW' },
            { img: 85, loc: 'A5', dir: 'N' },
            { img: 86, loc: 'K5', dir: 'N' },
            { img: 87, loc: 'K18', dir: 'W' },
            { img: 88, loc: 'G8', dir: 'N' },
            { img: 89, loc: 'F5', dir: 'N' },
            { img: 90, loc: 'G13', dir: 'N' },
            { img: 91, loc: 'E18', dir: 'N' },
            { img: 92, loc: 'J6', dir: 'S' },
            { img: 93, loc: 'D14', dir: 'N' },
            { img: 94, loc: 'C11', dir: 'W' },
            { img: 95, loc: 'C6', dir: 'S' },
            { img: 96, loc: 'F16', dir: 'S' },
            { img: 97, loc: 'D5', dir: 'NW' },
            { img: 98, loc: 'A15', dir: 'N' },
            { img: 99, loc: 'B18', dir: 'SE' },
            { img: 100, loc: 'H16', dir: 'N' },
            { img: 101, loc: 'B15', dir: 'N' },
            { img: 102, loc: 'J12', dir: 'NE' },
            { img: 103, loc: 'J13', dir: 'N' },
            { img: 104, loc: 'K16', dir: 'N' },
            { img: 105, loc: 'F13', dir: 'NW' },
            { img: 106, loc: 'E16', dir: 'NW' },
            { img: 107, loc: 'I7', dir: 'NE' },
            { img: 108, loc: 'I15', dir: 'NW' },
            { img: 109, loc: 'I9', dir: 'SE' },
            { img: 110, loc: 'E12', dir: 'NE' },
            { img: 111, loc: 'H5', dir: 'NW' },
            { img: 112, loc: 'G15', dir: 'NW' },
            { img: 113, loc: 'J7', dir: 'N' },
            { img: 114, loc: 'H12', dir: 'NW' },
            { img: 115, loc: 'G17', dir: 'N' },
            { img: 116, loc: 'E9', dir: 'NE' },
            { img: 117, loc: 'J16', dir: 'E' },
            { img: 118, loc: 'F11', dir: 'NE' },
            { img: 119, loc: 'D11', dir: 'SW' },
            { img: 120, loc: 'I10', dir: 'N' },
            { img: 121, loc: 'K9', dir: 'N' },
            { img: 122, loc: 'E8', dir: 'N' },
            { img: 123, loc: 'A14', dir: 'NW' },
            { img: 124, loc: 'I14', dir: 'NW' },
            { img: 125, loc: 'C5', dir: 'N' },
            { img: 126, loc: 'D15', dir: 'NW' },
            { img: 127, loc: 'E14', dir: 'E' },
            { img: 128, loc: 'G9', dir: 'NE' },
            { img: 129, loc: 'E6', dir: 'NW' },
            { img: 130, loc: 'J5', dir: 'NW' },
            { img: 131, loc: 'H8', dir: 'NE' },
            { img: 132, loc: 'I18', dir: 'NE' },
            { img: 133, loc: 'A9', dir: 'NW' },
            { img: 134, loc: 'G6', dir: 'SW' },
            { img: 135, loc: 'C8', dir: 'NW' },
            { img: 136, loc: 'D18', dir: 'N' },
            { img: 137, loc: 'G14', dir: 'E' },
            { img: 138, loc: 'C13', dir: 'NW' },
            { img: 139, loc: 'A18', dir: 'N' },
            { img: 140, loc: 'H10', dir: 'NE' },
            { img: 141, loc: 'G4', dir: 'N' },
            { img: 142, loc: 'B12', dir: 'SE' },
            { img: 143, loc: 'C16', dir: 'N' },
            { img: 144, loc: 'K14', dir: 'NE' },
            { img: 145, loc: 'G10', dir: 'NE' },
            { img: 146, loc: 'D7', dir: 'S' },
            { img: 147, loc: 'B6', dir: 'NW' },
            { img: 148, loc: 'B10', dir: 'SE' },
            { img: 149, loc: 'H13', dir: 'SW' }
        ],
        holds2017: [
            { img: 1, loc: 'J10', dir: 'E' },
            { img: 2, loc: 'J8', dir: 'N' },
            { img: 4, loc: 'G1', dir: 'E' },
            { img: 5, loc: 'H6', dir: 'N' },
            { img: 6, loc: 'A13', dir: 'E' },
            { img: 7, loc: 'B17', dir: 'N' },
            { img: 8, loc: 'C3', dir: 'W' },
            { img: 11, loc: 'F16', dir: 'N' },
            { img: 12, loc: 'C8', dir: 'N' },
            { img: 13, loc: 'C5', dir: 'S' },
            { img: 14, loc: 'E2', dir: 'S' },
            { img: 15, loc: 'J1', dir: 'N' },
            { img: 16, loc: 'I17', dir: 'N' },
            { img: 18, loc: 'B6', dir: 'N' },
            { img: 19, loc: 'C2', dir: 'S' },
            { img: 20, loc: 'B16', dir: 'NE' },
            { img: 21, loc: 'H4', dir: 'SE' },
            { img: 22, loc: 'C15', dir: 'NW' },
            { img: 23, loc: 'J3', dir: 'NE' },
            { img: 25, loc: 'A9', dir: 'N' },
            { img: 26, loc: 'F11', dir: 'NE' },
            { img: 27, loc: 'I14', dir: 'E' },
            { img: 28, loc: 'K18', dir: 'N' },
            { img: 29, loc: 'H2', dir: 'S' },
            { img: 30, loc: 'G18', dir: 'N' },
            { img: 31, loc: 'D11', dir: 'NW' },
            { img: 32, loc: 'F14', dir: 'N' },
            { img: 33, loc: 'F13', dir: 'W' },
            { img: 34, loc: 'F10', dir: 'SW' },
            { img: 35, loc: 'C4', dir: 'N' },
            { img: 36, loc: 'K5', dir: 'SW' },
            { img: 37, loc: 'K12', dir: 'N' },
            { img: 38, loc: 'D1', dir: 'W' },
            { img: 40, loc: 'B7', dir: 'N' },

            { img: 41, loc: 'E13', dir: 'N' }, // actualy #201 (red hold)

            { img: 51, loc: 'K17', dir: 'NE' },
            { img: 52, loc: 'G17', dir: 'N' },
            { img: 53, loc: 'D17', dir: 'N' },
            { img: 54, loc: 'I12', dir: 'E' },
            { img: 56, loc: 'F4', dir: 'N' },
            { img: 57, loc: 'K3', dir: 'SE' },
            { img: 58, loc: 'A16', dir: 'NW' },
            { img: 59, loc: 'J4', dir: 'N' },
            { img: 60, loc: 'A15', dir: 'N' },
            { img: 61, loc: 'B2', dir: 'SW' },
            { img: 62, loc: 'K1', dir: 'SE' },
            { img: 63, loc: 'E6', dir: 'N' },
            { img: 64, loc: 'F2', dir: 'S' },
            { img: 65, loc: 'G3', dir: 'N' },
            { img: 66, loc: 'B4', dir: 'N' },
            { img: 67, loc: 'B1', dir: 'S' },
            { img: 68, loc: 'B14', dir: 'E' },
            { img: 69, loc: 'J7', dir: 'SE' },
            { img: 70, loc: 'A3', dir: 'N' },
            { img: 71, loc: 'I5', dir: 'SE' },
            { img: 72, loc: 'H9', dir: 'N' },
            { img: 73, loc: 'B8', dir: 'SW' },
            { img: 74, loc: 'E11', dir: 'SE' },
            { img: 75, loc: 'E8', dir: 'N' },
            { img: 76, loc: 'A11', dir: 'N' },
            { img: 77, loc: 'A18', dir: 'N' },
            { img: 78, loc: 'G14', dir: 'N' },
            { img: 79, loc: 'G6', dir: 'NE' },
            { img: 80, loc: 'K15', dir: 'E' },
            { img: 82, loc: 'C10', dir: 'W' },
            { img: 83, loc: 'D9', dir: 'NW' },
            { img: 84, loc: 'K13', dir: 'NE' },
            { img: 85, loc: 'H1', dir: 'SE' },
            { img: 86, loc: 'I8', dir: 'NE' },
            { img: 87, loc: 'F5', dir: 'N' },
            { img: 88, loc: 'I16', dir: 'NW' },
            { img: 89, loc: 'H10', dir: 'E' },
            { img: 90, loc: 'C13', dir: 'NW' },
            { img: 91, loc: 'H18', dir: 'N' },
            { img: 99, loc: 'G7', dir: 'NW' },
            { img: 100, loc: 'D3', dir: 'SW' },
            { img: 102, loc: 'C1', dir: 'S' },
            { img: 103, loc: 'H17', dir: 'N' },
            { img: 105, loc: 'H14', dir: 'N' },
            { img: 106, loc: 'H15', dir: 'N' },
            { img: 107, loc: 'K16', dir: 'NE' },
            { img: 108, loc: 'K8', dir: 'N' },
            { img: 109, loc: 'F1', dir: 'S' },
            { img: 110, loc: 'E14', dir: 'NE' },
            { img: 111, loc: 'A8', dir: 'NW' },
            { img: 112, loc: 'I4', dir: 'NE' },
            { img: 113, loc: 'A2', dir: 'S' },
            { img: 114, loc: 'F3', dir: 'SE' },
            { img: 115, loc: 'D6', dir: 'N' },
            { img: 116, loc: 'C17', dir: 'NW' },
            { img: 117, loc: 'G16', dir: 'NW' },
            { img: 118, loc: 'F7', dir: 'N' },
            { img: 119, loc: 'D5', dir: 'W' },
            { img: 122, loc: 'G4', dir: 'N' },
            { img: 123, loc: 'J6', dir: 'N' },
            { img: 124, loc: 'G10', dir: 'NW' },
            { img: 125, loc: 'B9', dir: 'N' },
            { img: 126, loc: 'G8', dir: 'NW' },
            { img: 127, loc: 'K9', dir: 'NE' },
            { img: 128, loc: 'D18', dir: 'N' },
            { img: 129, loc: 'C7', dir: 'N' },
            { img: 130, loc: 'F12', dir: 'S' },
            { img: 131, loc: 'D12', dir: 'NW' },
            { img: 132, loc: 'D15', dir: 'NE' },
            { img: 133, loc: 'K11', dir: 'N' },
            { img: 134, loc: 'I2', dir: 'SE' },
            { img: 135, loc: 'B10', dir: 'NW' },
            { img: 136, loc: 'G13', dir: 'NE' },
            { img: 137, loc: 'H11', dir: 'NE' },
            { img: 138, loc: 'B13', dir: 'N' },
            { img: 139, loc: 'J13', dir: 'NE' },
            { img: 140, loc: 'A5', dir: 'NW' },
            { img: 141, loc: 'F18', dir: 'N' },
            { img: 147, loc: 'H3', dir: 'SE' },
            { img: 148, loc: 'E4', dir: 'NE' },
            { img: 150, loc: 'K14', dir: 'NE' },
            { img: 151, loc: 'D14', dir: 'NE' },
            { img: 152, loc: 'C12', dir: 'SW' },
            { img: 153, loc: 'I1', dir: 'SW' },
            { img: 154, loc: 'H8', dir: 'NE' },
            { img: 155, loc: 'E1', dir: 'W' },
            { img: 156, loc: 'K6', dir: 'N' },
            { img: 157, loc: 'A4', dir: 'NW' },
            { img: 158, loc: 'D2', dir: 'NW' },
            { img: 159, loc: 'K2', dir: 'S' },
            { img: 160, loc: 'G2', dir: 'S' },
            { img: 161, loc: 'F6', dir: 'NW' },
            { img: 162, loc: 'E17', dir: 'SW' },
            { img: 163, loc: 'G11', dir: 'NW' },
            { img: 164, loc: 'F15', dir: 'NW' },
            { img: 165, loc: 'E3', dir: 'SW' },
            { img: 166, loc: 'I3', dir: 'SE' },
            { img: 167, loc: 'J2', dir: 'NE' },
            { img: 168, loc: 'I15', dir: 'S' },
            { img: 169, loc: 'J9', dir: 'NE' },
            { img: 170, loc: 'B18', dir: 'NW' },
            { img: 171, loc: 'D10', dir: 'NW' },
            { img: 172, loc: 'F8', dir: 'N' },
            { img: 173, loc: 'A14', dir: 'N' },
            { img: 174, loc: 'J17', dir: 'SE' },
            { img: 175, loc: 'A6', dir: 'N' },
            { img: 176, loc: 'J16', dir: 'N' },
            { img: 177, loc: 'E10', dir: 'E' },
            { img: 178, loc: 'C14', dir: 'NW' },
            { img: 179, loc: 'I13', dir: 'SE' },
            { img: 180, loc: 'E16', dir: 'S' },
            { img: 181, loc: 'A17', dir: 'N' },
            { img: 182, loc: 'F17', dir: 'N' },
            { img: 183, loc: 'A12', dir: 'N' },
            { img: 184, loc: 'B11', dir: 'NW' },
            { img: 185, loc: 'A1', dir: 'SW' },
            { img: 186, loc: 'H12', dir: 'N' },
            { img: 187, loc: 'D8', dir: 'SW' },
            { img: 188, loc: 'E7', dir: 'N' },
            { img: 189, loc: 'I7', dir: 'NE' },
            { img: 190, loc: 'I10', dir: 'NW' },
            { img: 191, loc: 'J14', dir: 'S' },
            { img: 192, loc: 'F9', dir: 'N' },
            { img: 193, loc: 'D4', dir: 'NW' },
            { img: 194, loc: 'H5', dir: 'E' },
            { img: 195, loc: 'J11', dir: 'NE' },
            { img: 196, loc: 'J18', dir: 'N' },
            { img: 197, loc: 'C16', dir: 'NE' },
            { img: 198, loc: 'E18', dir: 'N' },
            { img: 199, loc: 'B3', dir: 'SW' },
            { img: 200, loc: 'K4', dir: 'NE' },

            // Wood Holds
            { img: 201, loc: 'H7', dir: 'SW' },
            { img: 202, loc: 'D7', dir: 'SE' },
            { img: 203, loc: 'I18', dir: 'W' },
            { img: 204, loc: 'C18', dir: 'E' },
            { img: 205, loc: 'G12', dir: 'E' },
            { img: 206, loc: 'E12', dir: 'W' },
            { img: 207, loc: 'J15', dir: 'SE' },
            { img: 208, loc: 'B15', dir: 'SW' },
            { img: 209, loc: 'E15', dir: 'SW' },
            { img: 210, loc: 'G15', dir: 'SE' },
            { img: 211, loc: 'H13', dir: 'E' },
            { img: 212, loc: 'D13', dir: 'W' },
            { img: 213, loc: 'B5', dir: 'SW' },
            { img: 214, loc: 'J5', dir: 'SE' },
            { img: 215, loc: 'E9', dir: 'NE' },
            { img: 216, loc: 'G9', dir: 'NW' },
            { img: 217, loc: 'C11', dir: 'W' },
            { img: 218, loc: 'I11', dir: 'E' },
            { img: 219, loc: 'D16', dir: 'SW' },
            { img: 220, loc: 'H16', dir: 'SE' },
            { img: 221, loc: 'B12', dir: 'SW' },
            { img: 222, loc: 'J12', dir: 'SE' },
            { img: 223, loc: 'A7', dir: 'NE' },
            { img: 224, loc: 'K7', dir: 'NW' },
            { img: 225, loc: 'E5', dir: 'E' },
            { img: 226, loc: 'G5', dir: 'W' },
            { img: 227, loc: 'C9', dir: 'SW' },
            { img: 228, loc: 'I9', dir: 'SE' },
            { img: 229, loc: 'A10', dir: 'SW' },
            { img: 230, loc: 'K10', dir: 'SE' },
            { img: 231, loc: 'C6', dir: 'NE' },
            { img: 232, loc: 'I6', dir: 'NW' },
        ],
        holds2019: [
            { img: 1, loc: 'E2', dir: 'N' },
            { img: 2, loc: 'D6', dir: 'NW' },
            { img: 3, loc: 'B1', dir: 'NW' },
            { img: 4, loc: 'G3', dir: 'N' },
            { img: 5, loc: 'J16', dir: 'N' },
            { img: 7, loc: 'K5', dir: 'N' },
            { img: 8, loc: 'C1', dir: 'SE' },
            { img: 9, loc: 'K13', dir: 'W' },
            { img: 10, loc: 'D16', dir: 'NW' },
            { img: 11, loc: 'C4', dir: 'NW' },
            { img: 12, loc: 'D17', dir: 'SE' },
            { img: 13, loc: 'B4', dir: 'S' },
            { img: 14, loc: 'B15', dir: 'N' },
            { img: 15, loc: 'D13', dir: 'S' },
            { img: 17, loc: 'A17', dir: 'N' },
            { img: 18, loc: 'K18', dir: 'N' },
            { img: 19, loc: 'F1', dir: 'N' },
            { img: 20, loc: 'H17', dir: 'NE' },
            { img: 21, loc: 'A12', dir: 'N' },
            { img: 22, loc: 'H14', dir: 'N' },
            { img: 23, loc: 'K1', dir: 'S' },
            { img: 24, loc: 'K11', dir: 'NE' },
            { img: 25, loc: 'C7', dir: 'N' },
            { img: 26, loc: 'K3', dir: 'SE' },
            { img: 27, loc: 'G7', dir: 'NE' },
            { img: 28, loc: 'F18', dir: 'N' },
            { img: 29, loc: 'D2', dir: 'SW' },
            { img: 30, loc: 'H7', dir: 'N' },
            { img: 31, loc: 'J10', dir: 'NE' },
            { img: 32, loc: 'G4', dir: 'E' },
            { img: 33, loc: 'G11', dir: 'SE' },
            { img: 34, loc: 'D8', dir: 'S' },
            { img: 35, loc: 'F5', dir: 'N' },
            { img: 36, loc: 'B10', dir: 'SE' },
            { img: 37, loc: 'I1', dir: 'SE' },
            { img: 38, loc: 'I5', dir: 'N' },
            { img: 39, loc: 'E14', dir: 'NW' },
            { img: 40, loc: 'J7', dir: 'N' },

            { img: 51, loc: 'J6', dir: 'N' },
            { img: 52, loc: 'K4', dir: 'SE' },
            { img: 53, loc: 'I2', dir: 'SE' },
            { img: 54, loc: 'E12', dir: 'SW' },
            { img: 56, loc: 'F3', dir: 'SW' },
            { img: 57, loc: 'K15', dir: 'NE' },
            { img: 59, loc: 'K17', dir: 'NE' },
            { img: 60, loc: 'I3', dir: 'NE' },
            { img: 61, loc: 'J1', dir: 'S' },
            { img: 62, loc: 'H1', dir: 'N' },
            { img: 63, loc: 'G2', dir: 'SE' },
            { img: 64, loc: 'B7', dir: 'N' },
            { img: 65, loc: 'D4', dir: 'NW' },
            { img: 66, loc: 'A4', dir: 'N' },
            { img: 67, loc: 'F16', dir: 'NE' },
            { img: 68, loc: 'J14', dir: 'E' },
            { img: 69, loc: 'A6', dir: 'NE' },
            { img: 70, loc: 'B3', dir: 'SW' },
            { img: 71, loc: 'D1', dir: 'S' },
            { img: 72, loc: 'B16', dir: 'N' },
            { img: 73, loc: 'F8', dir: 'NW' },
            { img: 74, loc: 'G6', dir: 'SW' },
            { img: 75, loc: 'C12', dir: 'NW' },
            { img: 76, loc: 'F17', dir: 'N' },
            { img: 77, loc: 'A14', dir: 'N' },
            { img: 78, loc: 'E7', dir: 'NE' },
            { img: 79, loc: 'K10', dir: 'E' },
            { img: 80, loc: 'H16', dir: 'N' },
            { img: 81, loc: 'A2', dir: 'NE' },
            { img: 82, loc: 'D3', dir: 'SE' },
            { img: 83, loc: 'D10', dir: 'N' },
            { img: 84, loc: 'I18', dir: 'N' },
            { img: 85, loc: 'E17', dir: 'NW' },
            { img: 86, loc: 'I8', dir: 'N' },
            { img: 87, loc: 'H4', dir: 'NE' },
            { img: 88, loc: 'I13', dir: 'N' },
            { img: 89, loc: 'B5', dir: 'N' },
            { img: 90, loc: 'H12', dir: 'N' },
            { img: 91, loc: 'D18', dir: 'N' },
            { img: 99, loc: 'A9', dir: 'SE' },
            { img: 100, loc: 'E3', dir: 'SW' },
            { img: 102, loc: 'B2', dir: 'SW' },
            { img: 103, loc: 'A16', dir: 'NW' },
            { img: 105, loc: 'E5', dir: 'N' },
            { img: 106, loc: 'J2', dir: 'SE' },
            { img: 107, loc: 'K2', dir: 'SE' },
            { img: 108, loc: 'J17', dir: 'N' },
            { img: 109, loc: 'G1', dir: 'SE' },
            { img: 110, loc: 'H3', dir: 'E' },
            { img: 111, loc: 'F2', dir: 'S' },
            { img: 112, loc: 'J4', dir: 'E' },
            { img: 113, loc: 'A3', dir: 'SW' },
            { img: 114, loc: 'E9', dir: 'NE' },
            { img: 115, loc: 'C5', dir: 'NW' },
            { img: 116, loc: 'F6', dir: 'N' },
            { img: 117, loc: 'B17', dir: 'N' },
            { img: 118, loc: 'J8', dir: 'NW' },
            { img: 119, loc: 'A1', dir: 'SW' },
            { img: 122, loc: 'G15', dir: 'N' },
            { img: 123, loc: 'I16', dir: 'N' },
            { img: 124, loc: 'K9', dir: 'NW' },
            { img: 125, loc: 'H5', dir: 'NW' },
            { img: 126, loc: 'G10', dir: 'W' },
            { img: 127, loc: 'G17', dir: 'N' },
            { img: 128, loc: 'H18', dir: 'N' },
            { img: 129, loc: 'A18', dir: 'N' },
            { img: 130, loc: 'B11', dir: 'N' },
            { img: 131, loc: 'C8', dir: 'N' },
            { img: 132, loc: 'H2', dir: 'S' },
            { img: 133, loc: 'K8', dir: 'N' },
            { img: 134, loc: 'E1', dir: 'SW' },
            { img: 135, loc: 'C13', dir: 'N' },
            { img: 136, loc: 'F4', dir: 'N' },
            { img: 137, loc: 'C18', dir: 'E' },
            { img: 138, loc: 'D15', dir: 'N' },
            { img: 139, loc: 'E11', dir: 'NE' },
            { img: 140, loc: 'G9', dir: 'N' },
            { img: 141, loc: 'I15', dir: 'N' },
            { img: 147, loc: 'A8', dir: 'SW' },
            { img: 148, loc: 'C2', dir: 'NE' },

            // Wood Holds
            { img: 201, loc: 'I7', dir: 'SW' },
            { img: 202, loc: 'G18', dir: 'E' },
            { img: 203, loc: 'K6', dir: 'NW' },
            { img: 204, loc: 'G16', dir: 'E' },
            { img: 205, loc: 'F9', dir: 'NE' },
            { img: 206, loc: 'E16', dir: 'W' },
            { img: 207, loc: 'E4', dir: 'SW' },
            { img: 208, loc: 'E18', dir: 'W' },
            { img: 209, loc: 'I12', dir: 'NW' },
            { img: 210, loc: 'C10', dir: 'NE' },
            { img: 211, loc: 'A7', dir: 'E' },
            { img: 212, loc: 'J12', dir: 'W' },
            { img: 213, loc: 'B12', dir: 'SW' },
            { img: 214, loc: 'I11', dir: 'SE' },
            { img: 215, loc: 'C9', dir: 'NE' },
            { img: 216, loc: 'F11', dir: 'NW' },
            { img: 217, loc: 'K16', dir: 'W' },
            { img: 218, loc: 'F13', dir: 'SE' },
            { img: 219, loc: 'I4', dir: 'W' },
            { img: 220, loc: 'J13', dir: 'E' },
            { img: 221, loc: 'D14', dir: 'NW' },
            { img: 222, loc: 'C6', dir: 'NE' },
            { img: 223, loc: 'C11', dir: 'NE' },
            { img: 224, loc: 'D7', dir: 'NE' },
            { img: 225, loc: 'F7', dir: 'E' },
            { img: 226, loc: 'G14', dir: 'W' },
            { img: 227, loc: 'B9', dir: 'W' },
            { img: 228, loc: 'B13', dir: 'NE' },
            { img: 229, loc: 'I6', dir: 'NW' },
            { img: 230, loc: 'I10', dir: 'E' },
            { img: 231, loc: 'K12', dir: 'SE' },
            { img: 232, loc: 'H8', dir: 'NW' },
            { img: 233, loc: 'G8', dir: 'NE' },
            { img: 234, loc: 'E13', dir: 'W' },
            { img: 235, loc: 'K7', dir: 'W' },
            { img: 236, loc: 'C16', dir: 'W' },
            { img: 237, loc: 'B6', dir: 'W' },
            { img: 238, loc: 'A13', dir: 'E' },
            { img: 239, loc: 'I14', dir: 'SE' },
            { img: 240, loc: 'K14', dir: 'NW' },
            { img: 241, loc: 'E6', dir: 'E' },
            { img: 242, loc: 'D12', dir: 'W' },
            { img: 243, loc: 'A10', dir: 'NE' },
            { img: 244, loc: 'F10', dir: 'SW' },
            { img: 245, loc: 'H9', dir: 'W' },
            { img: 246, loc: 'H15', dir: 'S' },
            { img: 247, loc: 'C17', dir: 'NE' },
            { img: 248, loc: 'D5', dir: 'NE' },
            { img: 249, loc: 'B18', dir: 'E' },
            { img: 250, loc: 'J11', dir: 'W' },
            { img: 251, loc: 'A11', dir: 'NE' },
            { img: 252, loc: 'B8', dir: 'SE' },
            { img: 253, loc: 'G12', dir: 'SE' },
            { img: 254, loc: 'C14', dir: 'NE' },
            { img: 255, loc: 'J15', dir: 'SE' },
            { img: 256, loc: 'J18', dir: 'W' },
            { img: 257, loc: 'C15', dir: 'SW' },
            { img: 258, loc: 'B14', dir: 'NE' },
            { img: 259, loc: 'H13', dir: 'NW' },
            { img: 260, loc: 'H11', dir: 'SW' },
            { img: 261, loc: 'D11', dir: 'W' },
            { img: 262, loc: 'E8', dir: 'W' },
            { img: 263, loc: 'H6', dir: 'SW' },
            { img: 264, loc: 'I9', dir: 'NE' },
            { img: 265, loc: 'F14', dir: 'SE' },
            { img: 266, loc: 'C3', dir: 'NW' },
            { img: 267, loc: 'J3', dir: 'NE' },
            { img: 268, loc: 'J5', dir: 'NE' },
            { img: 269, loc: 'E15', dir: 'SW' },
            { img: 270, loc: 'I17', dir: 'NW' },
            { img: 271, loc: 'F12', dir: 'S' },
            { img: 272, loc: 'J9', dir: 'NW' },
            { img: 273, loc: 'F15', dir: 'NE' },
            { img: 274, loc: 'G13', dir: 'W' },
            { img: 275, loc: 'D9', dir: 'NE' },
            { img: 276, loc: 'E10', dir: 'SE' },
            { img: 277, loc: 'A15', dir: 'NE' },
            { img: 278, loc: 'H10', dir: 'NW' },
            { img: 279, loc: 'G5', dir: 'E' },
            { img: 280, loc: 'A5', dir: 'W' }
        ],
        xcoords: {
            A: 62,
            B: 94,
            C: 128,
            D: 160,
            E: 193,
            F: 226,
            G: 259,
            H: 292,
            I: 325,
            J: 357,
            K: 390,
        },
        ycoords: {
            '1': 616,
            '2': 582,
            '3': 549,
            '4': 516,
            '5': 484,
            '6': 451,
            '7': 417,
            '8': 385,
            '9': 352,
            '10': 319,
            '11': 287,
            '12': 254,
            '13': 221,
            '14': 189,
            '15': 155,
            '16': 122,
            '17': 89,
            '18': 56,
        },
        rotation: {
            'N': 0,
            'NE': 45,
            'E': 90,
            'SE': 135,
            'S': 180,
            'SW': 225,
            'W': 270,
            'NW': 315,
        }
    };

    var canvas = null;
    var stage = null;
    var borders = [];
    var containers = null;

    var images = null;

    function drawBoard(loaded) {
        canvas = document.getElementById("problemCanvas");
        stage = new createjs.Stage(canvas);
        borders = [];
        containers = new Map();
    
        var background = new createjs.Bitmap('data:image/png;base64,'+images[0]);
        background.scaleX = 0.66;
        background.scaleY = 0.66;
        stage.addChild(background);
        
        _.each(board.holdsZZZZ, function(hold) {
            var img = new Image();
            img.src = 'data:image/png;base64,'+images[hold.img];
            img.onload = function (event) {
                var container = new createjs.Container();
                container.regX = (this.width / 2);
                container.regY = (this.height / 2);
                container.x = board.xcoords[hold.loc.substring(0, 1)];
                container.y = board.ycoords[hold.loc.substring(1)];
                container.rotation = board.rotation[hold.dir];
                container.z = 1;
                container.scaleX = 0.666;
                container.scaleY = 0.666;
    
                var bmp = new createjs.Bitmap(this);
                container.addChild(bmp);
                stage.addChild(container);
                
                containers.set(hold.loc, container);
                if (containers.size == board.holdsZZZZ.length) {
                    stage.update();
                    loaded.resolve();
                }
            };
        });
    }

    function setHolds(holds, color)  {
        _.each(holds, function(loc, id) {
            var container = containers.get(loc);
            var border = new createjs.Shape();
            border.graphics.setStrokeStyle(6).beginStroke(color).drawCircle(container.regX, container.regY, 30);
            container.addChild(border);
            container.z = 2;
            borders.push(border);
        });
    }

    return {
        load: function() {
            var loaded = $q.defer();
            $document.ready(function() {
                if (images === null) {
                    database.images(function(img) {
                        images = img;
                        drawBoard(loaded);
                    });
                } else {
                    drawBoard(loaded);
                }
            });
            return loaded.promise;
        },
        set: function(holds) {
            _.each(borders, function(border) {
                border.parent.removeChild(border);
            });
            borders = [];

            var h = holds.split(',');
            setHolds(h[0].match(/([A-Z][0-9]+)/g), "rgba(0,0,0,1)");
            setHolds(h[1].match(/([A-Z][0-9]+)/g), "rgba(255,57,0,1)");
            setHolds(h[2].match(/([A-Z][0-9]+)/g), "rgba(0,0,0,1)");

            // Sort the children so that the board (z==0) is at the bottom
            // of the canvas, holds without borders are in the middle, and
            // holds with borders are on top.  This way the borders (circles)
            // are layered on top of any holds not in use by the problem.
            stage.sortChildren(function(a, b) {
                return a.z - b.z;
            });
            stage.update();
        }
    };
});
